# Generated by Django 4.2.2 on 2023-07-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
